/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsSubnavbarRouteImport } from './routes/components/Subnavbar'
import { Route as AuthRecoderRouteImport } from './routes/_auth/recoder'
import { Route as AuthQuestionnaireParserRouteImport } from './routes/_auth/questionnaireParser'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthCrosstablesRouteImport } from './routes/_auth/crosstables'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSubnavbarRoute = ComponentsSubnavbarRouteImport.update({
  id: '/components/Subnavbar',
  path: '/components/Subnavbar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoderRoute = AuthRecoderRouteImport.update({
  id: '/recoder',
  path: '/recoder',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQuestionnaireParserRoute = AuthQuestionnaireParserRouteImport.update({
  id: '/questionnaireParser',
  path: '/questionnaireParser',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCrosstablesRoute = AuthCrosstablesRouteImport.update({
  id: '/crosstables',
  path: '/crosstables',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crosstables': typeof AuthCrosstablesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/projects': typeof AuthProjectsRoute
  '/questionnaireParser': typeof AuthQuestionnaireParserRoute
  '/recoder': typeof AuthRecoderRoute
  '/components/Subnavbar': typeof ComponentsSubnavbarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crosstables': typeof AuthCrosstablesRoute
  '/dashboard': typeof AuthDashboardRoute
  '/projects': typeof AuthProjectsRoute
  '/questionnaireParser': typeof AuthQuestionnaireParserRoute
  '/recoder': typeof AuthRecoderRoute
  '/components/Subnavbar': typeof ComponentsSubnavbarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/crosstables': typeof AuthCrosstablesRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/projects': typeof AuthProjectsRoute
  '/_auth/questionnaireParser': typeof AuthQuestionnaireParserRoute
  '/_auth/recoder': typeof AuthRecoderRoute
  '/components/Subnavbar': typeof ComponentsSubnavbarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crosstables'
    | '/dashboard'
    | '/projects'
    | '/questionnaireParser'
    | '/recoder'
    | '/components/Subnavbar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crosstables'
    | '/dashboard'
    | '/projects'
    | '/questionnaireParser'
    | '/recoder'
    | '/components/Subnavbar'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/crosstables'
    | '/_auth/dashboard'
    | '/_auth/projects'
    | '/_auth/questionnaireParser'
    | '/_auth/recoder'
    | '/components/Subnavbar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ComponentsSubnavbarRoute: typeof ComponentsSubnavbarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/Subnavbar': {
      id: '/components/Subnavbar'
      path: '/components/Subnavbar'
      fullPath: '/components/Subnavbar'
      preLoaderRoute: typeof ComponentsSubnavbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/recoder': {
      id: '/_auth/recoder'
      path: '/recoder'
      fullPath: '/recoder'
      preLoaderRoute: typeof AuthRecoderRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/questionnaireParser': {
      id: '/_auth/questionnaireParser'
      path: '/questionnaireParser'
      fullPath: '/questionnaireParser'
      preLoaderRoute: typeof AuthQuestionnaireParserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/crosstables': {
      id: '/_auth/crosstables'
      path: '/crosstables'
      fullPath: '/crosstables'
      preLoaderRoute: typeof AuthCrosstablesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCrosstablesRoute: typeof AuthCrosstablesRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProjectsRoute: typeof AuthProjectsRoute
  AuthQuestionnaireParserRoute: typeof AuthQuestionnaireParserRoute
  AuthRecoderRoute: typeof AuthRecoderRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCrosstablesRoute: AuthCrosstablesRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthQuestionnaireParserRoute: AuthQuestionnaireParserRoute,
  AuthRecoderRoute: AuthRecoderRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ComponentsSubnavbarRoute: ComponentsSubnavbarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
